# Preamble
# This assumes you have a media folder mounted in the system and addressable 
# if mounted you need to set the mountpoint with uid and gid =1000
# mount //192.168.1.252/Public/Media /media/ -t cifs -o uid=1000,gid=1000,file_mode=0770,dir_mode=0770,rw,guest,_netdev
#

services:       

# ██████╗ ██████╗  ██████╗ ██╗    ██╗██╗      █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔═══██╗██║    ██║██║     ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
# ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
# ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═
# Indexer for torrents/usenets
                              
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${ARRPATH}Prowlarr/config:/config
      - ${ARRPATH}Prowlarr/backup:/data/Backup
      - ${ARRPATH}Downloads:/data/downloads
    ports:
      - 9696:9696
    restart: unless-stopped
    env_file:
      - '.env'
      
# ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
# ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
# ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
# ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
# ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                                 
# Organizes Series and downloads from qBittorrent
      
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${ARRPATH}Sonarr/config:/config
      - ${ARRPATH}Sonarr/backup:/data/Backup
      - ${MEDIAPATH}Kids/Series:/data/kidsshows
      - ${MEDIAPATH}TVshows:/data/tvshows
      - ${MEDIAPATH}Asian/TVshows:/data/Asiantvshows
      - ${ARRPATH}Downloads:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                              
# Organizes Movies and downloads from qBittorrent
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - ${ARRPATH}Radarr/config:/config
      - ${MEDIAPATH}Movies:/data/movies
      - ${MEDIAPATH}Asian/Movies:/data/Asianmovies
      - ${MEDIAPATH}Kids/Filmes:/data/kidsmovies
      - ${MEDIAPATH}Kids/Music:/data/kidsMusicVideos
      - ${ARRPATH}Radarr/backup:/data/Backup
      - ${ARRPATH}Downloads:/media/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██╗     ██╗██████╗  █████╗ ██████╗ ██████╗ 
# ██║     ██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██║     ██║██║  ██║███████║██████╔╝██████╔╝
# ██║     ██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ███████╗██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
# Organizes Music and downloads from qBittorrent
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    volumes:
      - ${ARRPATH}Lidarr/config:/config
      - ${MEDIAPATH}Music:/data/musicfolder
      - ${ARRPATH}Lidarr/backup:/data/Backup
      - ${ARRPATH}Downloads:/data/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗ ███████╗ █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝█████╗  ███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══╝  ██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║███████╗██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
# Organizes Books/Audiobooks and downloads from qBittorrent                                                                                                                   
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    volumes:
      - ${ARRPATH}Readarr/config:/config
      - ${MEDIAPATH}Books:/data/books
      - ${ARRPATH}Readarr/backup:/data/Backup
      - ${ARRPATH}Downloads:/data/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    env_file:
      - '.env'

# ██╗  ██╗ ██████╗ ███╗   ███╗ █████╗ ██████╗ ██████╗ 
# ██║  ██║██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔══██╗
# ███████║██║   ██║██╔████╔██║███████║██████╔╝██████╔╝
# ██╔══██║██║   ██║██║╚██╔╝██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
# Dashboard / homepage front for arr - Not needed -@eddy        
#
#  homarr:
#    container_name: homarr
#    image: ghcr.io/ajnart/homarr:latest
#    restart: unless-stopped
#    volumes:
#      - ${ARRPATH}Homarr/configs:/app/data/configs
#      - ${ARRPATH}Homarr/icons:/app/public/icons
#      - ${ARRPATH}Homarr/data:/data
#    ports:
#      - '7575:7575'
#    env_file:
#      - '.env'

                                                                            
#
#      ██╗███████╗██╗     ██╗  ██╗   ██╗███████╗██╗███╗   ██╗
#      ██║██╔════╝██║     ██║  ╚██╗ ██╔╝██╔════╝██║████╗  ██║
#      ██║█████╗  ██║     ██║   ╚████╔╝ █████╗  ██║██╔██╗ ██║
# ██   ██║██╔══╝  ██║     ██║    ╚██╔╝  ██╔══╝  ██║██║╚██╗██║
# ╚█████╔╝███████╗███████╗███████╗██║   ██║     ██║██║ ╚████║
#  ╚════╝ ╚══════╝╚══════╝╚══════╝╚═╝   ╚═╝     ╚═╝╚═╝  ╚═══╝
# Main media server                                                                            
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - '8096:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    volumes:
      - ${ARRPATH}Jellyfin/config:/config
      - ${MEDIAPATH}Movies:/data/Movies
      - ${MEDIAPATH}TVShows:/data/TVShows
      - ${MEDIAPATH}Music:/data/Music
      - ${MEDIAPATH}books:/data/Books
      - ${MEDIAPATH}:/media
    env_file:
      - '.env'
    restart: unless-stopped
                                                                                            
#  ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
# ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
# ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║   
# ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║   
# ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║   
#  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝                                                                                          
#
# REMOVED BY EDDY - USE REMOTE qbittorrent 
#
#  qbittorrent:
#    image: linuxserver/qbittorrent:latest
#    container_name: qbittorrent
#    hostname: qbittorrent
#    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=false"
#    volumes:
#      - ${ARRPATH}qbittorrent/config:/config
#      - ${ARRPATH}Downloads:/downloads
#    ports:
#      - 8080:8080
#      - 6881:6881
#      - 6881:6881/udp
#    environment:
#      - WEBUI_PORT=8080
#      - TORRENTING_PORT=6881
#    healthcheck:
#      start_period: 15s
#    env_file:
#      - '.env'

#     ██╗███████╗██╗     ██╗  ██╗   ██╗███████╗███████╗███████╗██████╗ 
#     ██║██╔════╝██║     ██║  ╚██╗ ██╔╝██╔════╝██╔════╝██╔════╝██╔══██╗
#     ██║█████╗  ██║     ██║   ╚████╔╝ ███████╗█████╗  █████╗  ██████╔╝
#██   ██║██╔══╝  ██║     ██║    ╚██╔╝  ╚════██║██╔══╝  ██╔══╝  ██╔══██╗
#╚█████╔╝███████╗███████╗███████╗██║   ███████║███████╗███████╗██║  ██║
# ╚════╝ ╚══════╝╚══════╝╚══════╝╚═╝   ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
# A neat frontend to make requests to radarr and sonarr

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ${ARRPATH}Jellyseer/config:/app/config
    env_file:
      - '.env'
    restart: unless-stopped

# ███████╗██╗      █████╗ ██████╗ ███████╗███████╗ ██████╗ ██╗    ██╗   ██╗███████╗██████╗ ██████╗ 
# ██╔════╝██║     ██╔══██╗██╔══██╗██╔════╝██╔════╝██╔═══██╗██║    ██║   ██║██╔════╝██╔══██╗██╔══██╗
# █████╗  ██║     ███████║██████╔╝█████╗  ███████╗██║   ██║██║    ██║   ██║█████╗  ██████╔╝██████╔╝
# ██╔══╝  ██║     ██╔══██║██╔══██╗██╔══╝  ╚════██║██║   ██║██║    ╚██╗ ██╔╝██╔══╝  ██╔══██╗██╔══██╗
# ██║     ███████╗██║  ██║██║  ██║███████╗███████║╚██████╔╝███████╗╚████╔╝ ███████╗██║  ██║██║  ██║
# ╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚══════╝ ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝
# needed for prowlerr to access some torrent/usenet sites
# without being blocked by cloudflare
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    ports:
      - 8191:8191
    restart: unless-stopped


# ██████╗  █████╗ ███████╗ █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗╚══███╔╝██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║  ███╔╝ ███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║ ███╔╝  ██╔══██║██╔══██╗██╔══██╗
# ██████╔╝██║  ██║███████╗██║  ██║██║  ██║██║  ██║
# ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
# Grabs Subtitles from the web for all your series/movies

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ARRPATH}bazarr/config:/config
      - ${ARRPATH}bazarr/backups:/data/backup
      - ${MEDIAPATH}Movies:/data/movies #optional
      - ${MEDIAPATH}Kids/Series:/data/kidsshows
      - ${MEDIAPATH}TVshows:/data/tvshows
      - ${MEDIAPATH}Asian/Movies:/data/Asianmovies
      - ${MEDIAPATH}Kids/Filmes:/data/kidsmovies
      - ${MEDIAPATH}Kids/Music:/data/kidsMusicVideos
      - ${ARRPATH}Downloads:/data/downloads
      - ${MEDIAPATH}Asian/TVshows:/data/Asiantvshows
    ports:
      - 6767:6767
    restart: unless-stopped
